image:
  file: .gitpod.dockerfile
tasks:
  - init: npm install
    command: >
      npm i -g @angular/cli &&
      ng analytics off &&
      npm i -g nodemon &&
      npm i -g json-server &&
      json-server --watch db.json
